# Generated by Django 2.1.4 on 2018-12-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('max_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgo_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('base_attack', models.IntegerField()),
                ('base_hp', models.IntegerField()),
                ('max_attack', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servants.Group')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servants.Kind')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servants.Rarity')),
            ],
        ),
    ]
