# Generated by Django 2.1.4 on 2018-12-22 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servant_X_GpTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servants.GpTier')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servants.Servant')),
            ],
        ),
    ]
