# Generated by Django 2.1.4 on 2018-12-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servants', '0002_gptier_servant_x_gptier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rarity',
            options={'verbose_name_plural': 'Rarities'},
        ),
        migrations.AddField(
            model_name='servant',
            name='max_hp',
            field=models.IntegerField(default=14259),
            preserve_default=False,
        ),
    ]
