# Generated by Django 2.1.4 on 2018-12-23 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servants', '0003_auto_20181223_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Servant_X_CommandCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servants.CommandCard')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servants.Servant')),
            ],
        ),
    ]
